### ISSUE TITLE
Idea: Awesome Bl.ocks.org Profiles

### ISSUE THREAD

**Issue by curran** [wbkd/awesome-d3#42]
Has anyone compiled a list of most epic bl.ocks.org profiles? I feel like that needs to be a thing, and this would be a great place for it. Here's a start:

# Awesome Bl.ocks.org Profiles

 * https://bl.ocks.org/1wheel
 * https://bl.ocks.org/ColinEberhardt
 * https://bl.ocks.org/HarryStevens
 * https://bl.ocks.org/LuisSevillano
 * https://bl.ocks.org/d3indepth
 * https://bl.ocks.org/emeeks
 * https://bl.ocks.org/enjalot
 * https://bl.ocks.org/fil
 * https://bl.ocks.org/mbostock
 * https://bl.ocks.org/micahstubbs
 * https://bl.ocks.org/nbremer
 * https://bl.ocks.org/nitaku
 * https://bl.ocks.org/susielu
 * https://bl.ocks.org/sxywu
 * https://bl.ocks.org/syntagmatic
 * https://bl.ocks.org/tomshanley
 * https://bl.ocks.org/vasturiano
 * https://bl.ocks.org/veltman
 * https://bl.ocks.org/zanarmstrong

**Comment by g-div** [comment]
Please follow #43
