### ISSUE TITLE
Add Crossfilter to the list

### ISSUE THREAD

**Issue by lobo-tuerto** [wbkd/awesome-d3#56]
Although old I think it's an awesome and inspiring piece of tech built with D3. Hopefully, will inspire a rewrite on D3 v4 someday.

http://square.github.io/crossfilter/

**Comment by curran** [comment]
Just want to clarify - Crossfilter is not built with D3. You can use Crossfilter and D3 together to build cool things, but Crossfilter itself has no dependency on any parts of D3.

Agreed, though, that it should be part of `awesome-d3`. It is an awesome additional external library that was essentially designed to work well with D3.

**Comment by moklick** [comment]
good idea. I think in this case we can make an exception.

**Comment by lobo-tuerto** [comment]
You are totally right @curran, sorry for my confusion.

Here is the link to the currently maintained version: https://github.com/crossfilter/crossfilter

**Comment by moklick** [comment]
thanks I updated the link
